### ISSUE TITLE
*** An error occurred during deployment plan generation. Deployment cannot continue. The Element or Annotation class SqlIndex does not contain the Property class Online.

### ISSUE THREAD

**Issue by RamaInfraOps** [Azure/sql-action#257]
Deployment failed with the following error 

Initializing deployment (Failed)
*** An error occurred during deployment plan generation. Deployment cannot continue.
The Element or Annotation class SqlIndex does not contain the Property class Online.

versions for ref:

"C:\Program Files\Microsoft SQL Server\160\DAC\bin\SqlPackage.exe" /version
162.1.167.1

Visual Studio Installer: 17.12.4

**Comment by zijchen** [comment]
This should be fixed in the latest version of SqlPackage

**Comment by dzsquared** [comment]
If you install SqlPackage 170.x and still receive this issue, please let us know
